import { RemovalPolicy } from 'aws-cdk-lib';
import { Secret } from 'aws-cdk-lib/aws-secretsmanager';
import type { ISecret } from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface AppSecretsProps {
  /** Names of the secrets written by the deploy script from the .env. */
  readonly names: { readonly jwtSecret?: string; readonly googleMapsApiKey?: string };
}

/**
 * Secrets of the application. A value that came from the .env is written by
 * the deploy script before the stack (so it never goes through the template)
 * and only referenced here by name. An empty `JWT_SECRET` becomes a secret
 * generated by the stack.
 */
export class AppSecrets extends Construct {
  readonly jwtSecret: ISecret;
  readonly googleMapsApiKey?: ISecret;

  constructor(scope: Construct, id: string, props: AppSecretsProps) {
    super(scope, id);

    if (props.names.jwtSecret) {
      this.jwtSecret = Secret.fromSecretNameV2(this, 'JwtSecret', props.names.jwtSecret);
    } else {
      const generated = new Secret(this, 'GeneratedJwtSecret', {
        description: 'JWT_SECRET do backend, gerado no deploy',
        generateSecretString: { passwordLength: 64, excludePunctuation: true },
      });
      generated.applyRemovalPolicy(RemovalPolicy.DESTROY);
      this.jwtSecret = generated;
    }

    if (props.names.googleMapsApiKey) {
      this.googleMapsApiKey = Secret.fromSecretNameV2(this, 'GoogleMapsApiKey', props.names.googleMapsApiKey);
    }
  }
}
