import {
  ENV_SIZES,
  MQ_DEPLOYMENT_MODES,
  QUEUE_TYPES,
  SIZE_PROFILES,
} from './profiles';
import type { EnvSize, MqDeploymentMode, QueueType } from './profiles';

/**
 * Configuration of the environment, read from the .env given at deploy time.
 * Holds no secret value: the secrets that come from the .env are in
 * `InfraSecrets`, used only by the deploy script (never by the stack).
 */
export interface InfraConfig {
  readonly envName: string;
  readonly account: string;
  readonly region: string;
  readonly domainName: string;
  readonly appSubdomain: string;
  /** `api.<APP_SUBDOMAIN>.<DOMAIN_NAME>`. */
  readonly apiDomainName: string;
  readonly size: EnvSize;
  readonly network: { readonly maxAzs: number };
  readonly backend: {
    readonly desiredCount: number;
    readonly maxCount: number;
    /** `DB_POOL_MAX` of each task: connections of its database pool. */
    readonly dbPoolMax: number;
    readonly cpu: number;
    readonly memory: number;
  };
  readonly database: { readonly instanceClass: string; readonly multiAz: boolean };
  readonly broker: {
    readonly instanceType: string;
    readonly deploymentMode: MqDeploymentMode;
    readonly engineVersion: string;
    readonly queueType: QueueType;
  };
  readonly logRetentionDays: number;
  readonly app: {
    /** Empty: any origin. */
    readonly corsOrigin: string;
    readonly orderSimulationDelayFactor: string;
    readonly seedOnDeploy: boolean;
    /** `DEV_TOOLS_ENABLED` of the backend: the admin development tools (load test). */
    readonly devToolsEnabled: boolean;
  };
  /**
   * Names of the secrets written by the deploy script from the .env values.
   * Missing: the value was empty (the JWT is then generated by the stack).
   */
  readonly appSecretNames: {
    readonly jwtSecret?: string;
    readonly googleMapsApiKey?: string;
  };
}

/** Secret values that came from the .env. */
export interface InfraSecrets {
  readonly jwtSecret?: string;
  readonly googleMapsApiKey?: string;
}

export interface LoadedInfraConfig {
  readonly config: InfraConfig;
  readonly secrets: InfraSecrets;
  readonly warnings: string[];
}

export class InfraConfigError extends Error {
  constructor(readonly problems: string[]) {
    super(
      `Configuração do ambiente inválida (${problems.length} problema(s)):\n` +
        problems.map((problem) => `  - ${problem}`).join('\n'),
    );
    this.name = 'InfraConfigError';
  }
}

/** Every variable read from the .env, documented in `apps/infra/.env.example`. */
export const INFRA_ENV_KEYS = [
  'AWS_ACCOUNT_ID',
  'AWS_REGION',
  'DOMAIN_NAME',
  'ENV_NAME',
  'APP_SUBDOMAIN',
  'ENV_SIZE',
  'BACKEND_DESIRED_COUNT',
  'BACKEND_MAX_COUNT',
  'BACKEND_CPU',
  'BACKEND_MEMORY',
  'DB_POOL_MAX',
  'DB_INSTANCE_CLASS',
  'DB_MULTI_AZ',
  'MQ_INSTANCE_TYPE',
  'MQ_DEPLOYMENT_MODE',
  'MQ_ENGINE_VERSION',
  'RABBITMQ_QUEUE_TYPE',
  'LOG_RETENTION_DAYS',
  'JWT_SECRET',
  'GOOGLE_MAPS_API_KEY',
  'CORS_ORIGIN',
  'ORDER_SIMULATION_DELAY_FACTOR',
  'SEED_ON_DEPLOY',
  'DEV_TOOLS_ENABLED',
] as const;

// Values accepted by CloudWatch Logs (and by `RetentionDays` of the CDK).
const LOG_RETENTION_DAYS = [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365];
// Fargate: memory (MiB) accepted by each CPU (units).
const FARGATE_MEMORY: Record<number, number[]> = {
  256: [512, 1024, 2048],
  512: range(1024, 4096, 1024),
  1024: range(2048, 8192, 1024),
  2048: range(4096, 16384, 1024),
  4096: range(8192, 30720, 1024),
};
const DNS_LABEL = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$/;
const DOMAIN = /^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/;
const ORIGIN = /^https?:\/\/[a-z0-9.-]+(:\d{1,5})?$/i;
const MIN_JWT_SECRET_LENGTH = 32;

export function appSecretName(envName: string, key: 'jwt-secret' | 'google-maps-api-key'): string {
  return `${envName}/app/${key}`;
}

/**
 * Validates the .env of the environment and resolves the defaults of the size
 * profile and the individual overrides. Pure: no I/O. Collects **every**
 * problem and throws a single `InfraConfigError` with all of them.
 */
export function loadInfraConfig(raw: Record<string, string | undefined>): LoadedInfraConfig {
  const problems: string[] = [];
  const warnings: string[] = [];
  const value = (key: string): string => (raw[key] ?? '').trim();

  const required = (key: string, pattern: RegExp, hint: string): string => {
    const text = value(key);
    if (!text) problems.push(`${key}: obrigatória (${hint})`);
    else if (!pattern.test(text)) problems.push(`${key}: "${text}" inválido (${hint})`);
    return text;
  };

  const optional = (key: string, fallback: string, pattern: RegExp, hint: string): string => {
    const text = value(key);
    if (!text) return fallback;
    if (!pattern.test(text)) problems.push(`${key}: "${text}" inválido (${hint})`);
    return text;
  };

  const oneOf = <T extends string>(key: string, fallback: T, accepted: readonly T[]): T => {
    const text = value(key);
    if (!text) return fallback;
    if (!(accepted as readonly string[]).includes(text)) {
      problems.push(`${key}: "${text}" inválido (valores aceitos: ${accepted.join(', ')})`);
      return fallback;
    }
    return text as T;
  };

  const integer = (key: string, fallback: number, min: number, max: number): number => {
    const text = value(key);
    if (!text) return fallback;
    const parsed = Number(text);
    if (!Number.isInteger(parsed) || parsed < min || parsed > max) {
      problems.push(`${key}: "${text}" inválido (inteiro de ${min} a ${max})`);
      return fallback;
    }
    return parsed;
  };

  const boolean = (key: string, fallback: boolean): boolean => {
    const text = value(key).toLowerCase();
    if (!text) return fallback;
    if (text !== 'true' && text !== 'false') {
      problems.push(`${key}: "${value(key)}" inválido (valores aceitos: true, false)`);
      return fallback;
    }
    return text === 'true';
  };

  const account = required('AWS_ACCOUNT_ID', /^\d{12}$/, 'conta AWS com 12 dígitos');
  const region = required('AWS_REGION', /^[a-z]{2}(-[a-z]+)+-\d$/, 'região AWS, por exemplo sa-east-1');
  const domainName = required(
    'DOMAIN_NAME',
    DOMAIN,
    'nome de uma hosted zone existente no Route 53, por exemplo exemplo.com.br',
  ).toLowerCase();

  const envName = optional('ENV_NAME', 'jaja', /^[a-z][a-z0-9-]{1,19}$/, 'de 2 a 20 caracteres: letras minúsculas, dígitos e hífen, começando por letra');
  const appSubdomain = optional('APP_SUBDOMAIN', 'jaja', DNS_LABEL, 'um rótulo DNS: letras minúsculas, dígitos e hífen');

  const size = oneOf<EnvSize>('ENV_SIZE', 'demo', ENV_SIZES);
  const profile = SIZE_PROFILES[size];

  const desiredCount = integer('BACKEND_DESIRED_COUNT', profile.backendDesiredCount, 1, 20);
  const maxCount = integer('BACKEND_MAX_COUNT', Math.max(profile.backendMaxCount, desiredCount), 1, 50);
  // Connections of the pool of each task (the sum over every task must fit in
  // `max_connections` of the RDS).
  const dbPoolMax = integer('DB_POOL_MAX', 10, 1, 100);
  if (maxCount < desiredCount) {
    problems.push(`BACKEND_MAX_COUNT: ${maxCount} menor que BACKEND_DESIRED_COUNT (${desiredCount})`);
  }

  const cpu = integer('BACKEND_CPU', profile.backendCpu, 256, 4096);
  const memory = integer('BACKEND_MEMORY', profile.backendMemory, 512, 30720);
  const memories = FARGATE_MEMORY[cpu];
  if (!memories) {
    problems.push(`BACKEND_CPU: "${cpu}" inválido (valores aceitos: ${Object.keys(FARGATE_MEMORY).join(', ')})`);
  } else if (!memories.includes(memory)) {
    problems.push(
      `BACKEND_MEMORY: ${memory} não combina com BACKEND_CPU ${cpu} (aceitos: ${memories[0]} a ${memories[memories.length - 1]} MiB, ${cpu === 256 ? 'em 512, 1024 ou 2048' : 'de 1024 em 1024'})`,
    );
  }

  const dbInstanceClass = optional('DB_INSTANCE_CLASS', profile.dbInstanceClass, /^[a-z0-9]+\.[a-z0-9]+$/, 'classe sem o prefixo db., por exemplo t4g.micro');
  const dbMultiAz = boolean('DB_MULTI_AZ', profile.dbMultiAz);

  const mqInstanceType = optional('MQ_INSTANCE_TYPE', profile.mqInstanceType, /^mq\.[a-z0-9]+\.[a-z0-9]+$/, 'por exemplo mq.m7g.medium');
  const mqDeploymentMode = oneOf<MqDeploymentMode>('MQ_DEPLOYMENT_MODE', profile.mqDeploymentMode, MQ_DEPLOYMENT_MODES);
  const mqEngineVersion = optional('MQ_ENGINE_VERSION', profile.mqEngineVersion, /^\d+\.\d+(\.\d+)?$/, 'por exemplo 4.2');
  const queueType = oneOf<QueueType>('RABBITMQ_QUEUE_TYPE', profile.queueType, QUEUE_TYPES);

  const logRetentionText = value('LOG_RETENTION_DAYS');
  let logRetentionDays = 3;
  if (logRetentionText) {
    const parsed = Number(logRetentionText);
    if (LOG_RETENTION_DAYS.includes(parsed)) logRetentionDays = parsed;
    else problems.push(`LOG_RETENTION_DAYS: "${logRetentionText}" inválido (valores aceitos: ${LOG_RETENTION_DAYS.join(', ')})`);
  }

  const jwtSecret = value('JWT_SECRET');
  if (jwtSecret && jwtSecret.length < MIN_JWT_SECRET_LENGTH) {
    problems.push(`JWT_SECRET: curto demais (mínimo de ${MIN_JWT_SECRET_LENGTH} caracteres; vazio gera um aleatório)`);
  }
  const googleMapsApiKey = value('GOOGLE_MAPS_API_KEY');

  const corsOrigin = value('CORS_ORIGIN')
    .split(',')
    .map((origin) => origin.trim().replace(/\/+$/, ''))
    .filter(Boolean);
  for (const origin of corsOrigin) {
    if (!ORIGIN.test(origin)) {
      problems.push(`CORS_ORIGIN: "${origin}" inválida (origem como http://localhost:3000, sem caminho)`);
    }
  }

  const delayFactorText = value('ORDER_SIMULATION_DELAY_FACTOR');
  if (delayFactorText) {
    const factor = Number(delayFactorText);
    if (!Number.isFinite(factor) || factor < 0 || factor > 10) {
      problems.push(`ORDER_SIMULATION_DELAY_FACTOR: "${delayFactorText}" inválido (número de 0 a 10)`);
    }
  }

  const seedOnDeploy = boolean('SEED_ON_DEPLOY', false);
  const devToolsEnabled = boolean('DEV_TOOLS_ENABLED', false);

  if (problems.length > 0) throw new InfraConfigError(problems);

  if (mqDeploymentMode === 'SINGLE_INSTANCE' && queueType === 'quorum') {
    warnings.push(
      'Broker em instância única com filas quorum: funciona, mas sem réplicas o quorum não traz ganho de disponibilidade.',
    );
  }
  if (mqDeploymentMode === 'CLUSTER_MULTI_AZ' && queueType === 'classic') {
    warnings.push(
      'Broker em cluster com filas classic: cada fila mora num só nó e fica indisponível se ele cair. Prefira RABBITMQ_QUEUE_TYPE="quorum".',
    );
  }
  if (seedOnDeploy) {
    warnings.push(
      'SEED_ON_DEPLOY="true": os usuários do seed têm senhas conhecidas e ficarão acessíveis pela API pública enquanto o ambiente existir.',
    );
  }
  if (devToolsEnabled) {
    warnings.push(
      'DEV_TOOLS_ENABLED="true": o teste de carga do admin (/admin/dev) fica ligado e cada pedido do teste é um pedido real, de um cliente ativo qualquer.',
    );
  }

  const config: InfraConfig = {
    envName,
    account,
    region,
    domainName,
    appSubdomain,
    apiDomainName: `api.${appSubdomain}.${domainName}`,
    size,
    network: { maxAzs: profile.maxAzs },
    backend: { desiredCount, maxCount, cpu, memory, dbPoolMax },
    database: { instanceClass: dbInstanceClass, multiAz: dbMultiAz },
    broker: {
      instanceType: mqInstanceType,
      deploymentMode: mqDeploymentMode,
      engineVersion: mqEngineVersion,
      queueType,
    },
    logRetentionDays,
    app: {
      corsOrigin: corsOrigin.join(','),
      orderSimulationDelayFactor: delayFactorText || '1',
      seedOnDeploy,
      devToolsEnabled,
    },
    appSecretNames: {
      ...(jwtSecret ? { jwtSecret: appSecretName(envName, 'jwt-secret') } : {}),
      ...(googleMapsApiKey ? { googleMapsApiKey: appSecretName(envName, 'google-maps-api-key') } : {}),
    },
  };

  return {
    config,
    secrets: {
      ...(jwtSecret ? { jwtSecret } : {}),
      ...(googleMapsApiKey ? { googleMapsApiKey } : {}),
    },
    warnings,
  };
}

function range(from: number, to: number, step: number): number[] {
  const values: number[] = [];
  for (let current = from; current <= to; current += step) values.push(current);
  return values;
}
