import {
  AggregateRoot,
  EntityProps,
  Id,
  Result,
  Text,
} from '@mentoria-360/shared'
import {
  CART_MAX_ITEMS,
  DELIVERY_FEE_CENTS,
  FREE_DELIVERY_THRESHOLD_CENTS,
} from '../../cart'
import { OrderDTO } from '../dto'
import {
  ORDER_DELIVERY_INSTRUCTIONS_MAX_LENGTH,
  ORDER_PAYMENT_METHODS,
  ORDER_RECIPIENT_NAME_MAX_LENGTH,
  ORDER_STATUSES,
  OrderErrors,
  OrderPaymentMethod,
  OrderStatus,
  orderStatusIndex,
} from '../errors'
import {
  OrderDeliveredEvent,
  OrderEvent,
  OrderOutForDeliveryEvent,
  OrderPaymentApprovedEvent,
  OrderPickingStartedEvent,
  OrderPlacedEvent,
  OrderStepEventInput,
  OrderStepStatus,
} from '../event'
import {
  OrderDeliveryAddress,
  OrderDeliveryAddressProps,
} from './order-delivery-address.vo'
import { OrderItem, OrderItemProps } from './order-item.vo'

export interface OrderProps extends EntityProps {
  customerId: string
  status: OrderStatus
  items: OrderItemProps[]
  deliveryAddress: OrderDeliveryAddressProps
  recipientName: string
  deliveryInstructions?: string | null
  placedAt: Date
  // Dates of the next steps; missing resolves to `null`.
  paymentApprovedAt?: Date | null
  pickingStartedAt?: Date | null
  outForDeliveryAt?: Date | null
  deliveredAt?: Date | null
}

// The prop that holds the date of each step of the sequence.
type OrderStepDateProp =
  | 'placedAt'
  | 'paymentApprovedAt'
  | 'pickingStartedAt'
  | 'outForDeliveryAt'
  | 'deliveredAt'

const ORDER_STEP_DATE_PROPS: Record<OrderStatus, OrderStepDateProp> = {
  PLACED: 'placedAt',
  PAYMENT_APPROVED: 'paymentApprovedAt',
  PICKING: 'pickingStartedAt',
  OUT_FOR_DELIVERY: 'outForDeliveryAt',
  DELIVERED: 'deliveredAt',
}

// The optional step dates, in the order of the sequence (`placedAt` is always
// required and checked on its own).
const ORDER_NEXT_STEP_STATUSES = ORDER_STATUSES.slice(1)

// What the customer's confirmation provides to `Order.place`; id, status and
// `placedAt` are generated.
export interface PlaceOrderProps {
  customerId: string
  items: OrderItemProps[]
  deliveryAddress: OrderDeliveryAddressProps
  recipientName: string
  deliveryInstructions?: string | null
}

// What the payment gateway reports when it approves the payment of the order.
export interface ApprovePaymentProps {
  transactionId: string
  paymentMethod: OrderPaymentMethod
}

// What the store reports when it starts picking the items.
export interface StartPickingProps {
  pickingListId: string
}

// What the delivery reports when a courier leaves with the order.
export interface DispatchProps {
  courierName: string
  trackingCode: string
  estimatedDeliveryAt: Date
}

// What the delivery reports when the order reaches the customer. Missing or
// blank `receivedBy` resolves to the recipient of the order.
export interface CompleteDeliveryProps {
  receivedBy?: string | null
}

// Minimum length of the recipient name, after trimming.
const ORDER_RECIPIENT_NAME_MIN_LENGTH = 2

// Maximum length, after trimming, of a code generated by an external system
// (the transaction of the gateway, the picking list, the tracking code).
const ORDER_EXTERNAL_CODE_MAX_LENGTH = 64

// An order belongs to a customer (`customerId`, never the user), which never
// changes. Items, prices, address and recipient are copies made when the order
// is placed and never follow later changes of the catalog or of the customer
// record. The totals are always computed from the items; the database stores
// them only for reading.
//
// The status follows the sequence of `ORDER_STATUSES`: `PLACED` →
// `PAYMENT_APPROVED` → `PICKING` → `OUT_FOR_DELIVERY` → `DELIVERED`, and only
// advances one step at a time. Each step has its date (`placedAt`,
// `paymentApprovedAt`, `pickingStartedAt`, `outForDeliveryAt`, `deliveredAt`),
// filled if and only if the order has reached the step.
//
// `place` creates a new order and adds `OrderPlacedEvent`. Each step of the
// cycle has a method of its own — `approvePayment`, `startPicking`, `dispatch`
// and `completeDelivery` —, always in the same order: validates the data of the
// step, advances one status through the **private** `advanceTo` (the only place
// that knows the sequence) and adds the event of its fact to the clone.
// `tryCreate` and `create` rehydrate a stored order and never add events.
// `cloneWith` carries the pending events to the clone, so behavior methods add
// their events to the returned instance and the original one never changes.
//
// The data of a step (the transaction of the payment, the picking list, the
// courier and the tracking code, who received the order) is data of external
// systems and lives only in the event of the step: the order keeps the status
// and the dates, which is what its screens read.
export class Order extends AggregateRoot<Order, OrderProps, OrderEvent> {
  private constructor(props: OrderProps) {
    super(props)
  }

  static create(props: OrderProps): Order {
    const result = Order.tryCreate(props)
    result.validator.throwsIfFailed()
    return result.instance
  }

  static tryCreate(props: OrderProps): Result<Order> {
    const input: Partial<OrderProps> = props ?? {}

    const id = Id.tryCreate(input.id)
    // `Id.tryCreate` would generate a uuid for a missing value.
    const customerId = Id.required(
      typeof input.customerId === 'string' ? input.customerId : '',
    )
    const status = Order.isValidStatus(input.status)
      ? Result.ok()
      : Result.fail(OrderErrors.ORDER_STATUS_INVALID)

    const items = (Array.isArray(input.items) ? input.items : []).map((item) =>
      OrderItem.tryCreate(item),
    )
    const itemsCount =
      items.length === 0
        ? Result.fail(OrderErrors.ORDER_ITEMS_REQUIRED)
        : items.length > CART_MAX_ITEMS
          ? Result.fail(OrderErrors.ORDER_ITEMS_LIMIT_EXCEEDED)
          : Result.ok()

    // Only the valid items are compared; the others fail with their own errors.
    const productIds = items
      .filter((item) => item.isOk)
      .map((item) => item.instance.productId)
    const uniqueProducts =
      new Set(productIds).size < productIds.length
        ? Result.fail(OrderErrors.ORDER_ITEM_DUPLICATED)
        : Result.ok()

    const deliveryAddress = OrderDeliveryAddress.tryCreate(
      input.deliveryAddress as OrderDeliveryAddressProps,
    )
    const recipientName = Text.tryCreate(input.recipientName as string, {
      minLength: ORDER_RECIPIENT_NAME_MIN_LENGTH,
      maxLength: ORDER_RECIPIENT_NAME_MAX_LENGTH,
    })
    // Missing or blank instructions resolve to `null`.
    const deliveryInstructions = Text.tryCreate(input.deliveryInstructions, {
      optional: true,
      maxLength: ORDER_DELIVERY_INSTRUCTIONS_MAX_LENGTH,
    })
    // `placedAt` is the moment the order entered `PLACED`; there is no code of
    // its own, since `place` always generates it and a stored order always has
    // it, so a missing or invalid date is reported as an invalid status.
    const placedAt = isValidDate(input.placedAt)
      ? Result.ok()
      : Result.fail(OrderErrors.ORDER_STATUS_INVALID)
    // Each next step date must be valid when present, and present if and only
    // if the status has reached the step; any inconsistency is an invalid
    // status. Only checked for a known status, which fails on its own otherwise.
    const stepDates = Order.isValidStatus(input.status)
      ? Order.checkStepDates(input.status, input)
      : Result.ok()

    const attrs = Result.combine([
      id,
      customerId,
      status,
      itemsCount,
      uniqueProducts,
      ...items,
      deliveryAddress,
      recipientName,
      deliveryInstructions,
      placedAt,
      stepDates,
    ])
    if (attrs.isFailure) return Result.fail([...new Set(attrs.errors)])

    return Result.ok(
      new Order({
        ...input,
        id: id.instance.value,
        customerId: customerId.instance.value,
        status: input.status as OrderStatus,
        items: items.map((item) => item.instance.toProps()),
        deliveryAddress: deliveryAddress.instance.toDTO(),
        recipientName: recipientName.instance.value,
        deliveryInstructions: deliveryInstructions.instance?.value ?? null,
        placedAt: new Date((input.placedAt as Date).getTime()),
        paymentApprovedAt: copyDate(input.paymentApprovedAt),
        pickingStartedAt: copyDate(input.pickingStartedAt),
        outForDeliveryAt: copyDate(input.outForDeliveryAt),
        deliveredAt: copyDate(input.deliveredAt),
      }),
    )
  }

  private static checkStepDates(
    status: OrderStatus,
    input: Partial<OrderProps>,
  ): Result<void> {
    const reached = orderStatusIndex(status)
    const consistent = ORDER_NEXT_STEP_STATUSES.every((step) => {
      const value = input[ORDER_STEP_DATE_PROPS[step]]
      const present = value !== undefined && value !== null
      if (present && !isValidDate(value)) return false
      return present === reached >= orderStatusIndex(step)
    })

    return consistent
      ? Result.ok()
      : Result.fail(OrderErrors.ORDER_STATUS_INVALID)
  }

  // A new order from the customer's confirmation: generates the id, `PLACED`
  // and `placedAt`, validates everything through `tryCreate` and, only when it
  // succeeds, adds exactly one `OrderPlacedEvent` to the created order.
  static place(props: PlaceOrderProps): Result<Order> {
    const input: Partial<PlaceOrderProps> = props ?? {}
    const now = new Date()

    const created = Order.tryCreate({
      id: Id.createUUID(),
      customerId: input.customerId as string,
      status: 'PLACED',
      items: input.items as OrderItemProps[],
      deliveryAddress: input.deliveryAddress as OrderDeliveryAddressProps,
      recipientName: input.recipientName as string,
      deliveryInstructions: input.deliveryInstructions,
      placedAt: now,
      createdAt: now,
      updatedAt: now,
    })
    if (created.isFailure) return created.withFail

    const order = created.instance
    const event = OrderPlacedEvent.tryCreate({
      orderId: order.id,
      customerId: order.customerId,
      items: order.items.map((item) => item.toDTO()),
      itemCount: order.itemCount,
      subtotalCents: order.subtotalCents,
      deliveryFeeCents: order.deliveryFeeCents,
      totalCents: order.totalCents,
      placedAt: order.placedAt,
    })
    if (event.isFailure) return event.withFail

    order.addEvent(event.instance)
    return Result.ok(order)
  }

  // One of `ORDER_STATUSES`.
  static isValidStatus(value: unknown): value is OrderStatus {
    return (ORDER_STATUSES as readonly unknown[]).includes(value)
  }

  // The payment gateway approved the payment: advances to `PAYMENT_APPROVED`
  // and adds `OrderPaymentApprovedEvent` with the data of the gateway and the
  // total of the order. A blank `transactionId`, one longer than 64 characters
  // or an unknown means of payment fail with `ORDER_PAYMENT_DATA_INVALID`,
  // without advancing and without event.
  approvePayment(
    props: ApprovePaymentProps,
    now: Date = new Date(),
  ): Result<Order> {
    const input: Partial<ApprovePaymentProps> = props ?? {}
    const transactionId = externalCode(input.transactionId)
    const paymentMethod = input.paymentMethod
    if (transactionId === null || !isPaymentMethod(paymentMethod)) {
      return Result.fail(OrderErrors.ORDER_PAYMENT_DATA_INVALID)
    }

    const advanced = this.advanceTo('PAYMENT_APPROVED', now)
    if (advanced.isFailure) return advanced.withFail

    const event = OrderPaymentApprovedEvent.tryCreate({
      ...this.stepEventInput(advanced.instance, 'PAYMENT_APPROVED'),
      transactionId,
      paymentMethod,
      amountCents: this.totalCents,
    })
    if (event.isFailure) return event.withFail

    advanced.instance.addEvent(event.instance)
    return advanced
  }

  // The store started picking the items: advances to `PICKING` and adds
  // `OrderPickingStartedEvent` with the picking list and the quantity of units
  // of the order. A blank `pickingListId` or one longer than 64 characters
  // fails with `ORDER_PICKING_DATA_INVALID`, without advancing and without
  // event.
  startPicking(props: StartPickingProps, now: Date = new Date()): Result<Order> {
    const input: Partial<StartPickingProps> = props ?? {}
    const pickingListId = externalCode(input.pickingListId)
    if (pickingListId === null) {
      return Result.fail(OrderErrors.ORDER_PICKING_DATA_INVALID)
    }

    const advanced = this.advanceTo('PICKING', now)
    if (advanced.isFailure) return advanced.withFail

    const event = OrderPickingStartedEvent.tryCreate({
      ...this.stepEventInput(advanced.instance, 'PICKING'),
      pickingListId,
      itemCount: this.itemCount,
    })
    if (event.isFailure) return event.withFail

    advanced.instance.addEvent(event.instance)
    return advanced
  }

  // A courier left with the order: advances to `OUT_FOR_DELIVERY` and adds
  // `OrderOutForDeliveryEvent`. A courier name outside 2 to 100 characters, a
  // blank `trackingCode` or one longer than 64 characters, and an estimate that
  // is not a valid date or is **before** the date of the step fail with
  // `ORDER_DISPATCH_DATA_INVALID`, without advancing and without event.
  dispatch(props: DispatchProps, now: Date = new Date()): Result<Order> {
    const input: Partial<DispatchProps> = props ?? {}
    const courierName = personName(input.courierName)
    const trackingCode = externalCode(input.trackingCode)
    const estimate = input.estimatedDeliveryAt
    const estimatedDeliveryAt =
      isValidDate(estimate) && estimate.getTime() >= now.getTime()
        ? estimate
        : null
    if (
      courierName === null ||
      trackingCode === null ||
      estimatedDeliveryAt === null
    ) {
      return Result.fail(OrderErrors.ORDER_DISPATCH_DATA_INVALID)
    }

    const advanced = this.advanceTo('OUT_FOR_DELIVERY', now)
    if (advanced.isFailure) return advanced.withFail

    const event = OrderOutForDeliveryEvent.tryCreate({
      ...this.stepEventInput(advanced.instance, 'OUT_FOR_DELIVERY'),
      courierName,
      trackingCode,
      estimatedDeliveryAt: new Date(estimatedDeliveryAt.getTime()),
    })
    if (event.isFailure) return event.withFail

    advanced.instance.addEvent(event.instance)
    return advanced
  }

  // The courier handed the order to the customer: advances to `DELIVERED` and
  // adds `OrderDeliveredEvent`. `receivedBy` is optional — missing, `null` or
  // blank resolves to the recipient of the order —, and, when informed, must be
  // text of 2 to 100 characters, failing with `ORDER_DELIVERY_DATA_INVALID`
  // otherwise, without advancing and without event.
  completeDelivery(
    props: CompleteDeliveryProps = {},
    now: Date = new Date(),
  ): Result<Order> {
    const input: Partial<CompleteDeliveryProps> = props ?? {}
    const informed = input.receivedBy
    // Missing, `null` and blank mean "no information"; anything else has to be
    // a name, so a value that is not text fails instead of being ignored.
    const notInformed =
      informed === undefined ||
      informed === null ||
      (typeof informed === 'string' && informed.trim().length === 0)
    const receivedBy = notInformed ? this.recipientName : personName(informed)
    if (receivedBy === null) {
      return Result.fail(OrderErrors.ORDER_DELIVERY_DATA_INVALID)
    }

    const advanced = this.advanceTo('DELIVERED', now)
    if (advanced.isFailure) return advanced.withFail

    const event = OrderDeliveredEvent.tryCreate({
      ...this.stepEventInput(advanced.instance, 'DELIVERED'),
      receivedBy,
    })
    if (event.isFailure) return event.withFail

    advanced.instance.addEvent(event.instance)
    return advanced
  }

  // Advances the order to `status`, which must be the **next** one of the
  // sequence: the current status, a previous one, a skipped step or any status
  // after `DELIVERED` fail with `ORDER_STATUS_TRANSITION_INVALID`. Returns a
  // clone with the status, the date of the step and `updatedAt` set to `now`,
  // **without any event**: the event of the fact is added by the step method
  // that called it. This instance never changes.
  //
  // Private on purpose: the sequence of the order is decided here, and nobody
  // outside the aggregate chooses the status it reaches.
  private advanceTo(status: OrderStepStatus, now: Date): Result<Order> {
    const next = ORDER_STATUSES[orderStatusIndex(this.status) + 1]
    if (next === undefined || status !== next) {
      return Result.fail(OrderErrors.ORDER_STATUS_TRANSITION_INVALID)
    }

    return this.cloneWith({
      status: next,
      [ORDER_STEP_DATE_PROPS[next]]: now,
      updatedAt: now,
    })
  }

  // The common part of the event of a step: the order, the customer, the status
  // before the step and the date the clone recorded for it.
  private stepEventInput(
    advanced: Order,
    status: OrderStepStatus,
  ): OrderStepEventInput {
    return {
      orderId: this.id,
      customerId: this.customerId,
      previousStatus: this.status,
      changedAt: advanced.dateOf(status) as Date,
    }
  }

  // Whether the order is in `status` or has already passed it. `false` for an
  // unknown status.
  hasReached(status: OrderStatus): boolean {
    return (
      Order.isValidStatus(status) &&
      orderStatusIndex(this.status) >= orderStatusIndex(status)
    )
  }

  // A copy of the date of the step, or `null` while the order has not reached
  // it.
  private dateOf(status: OrderStatus): Date | null {
    return copyDate(this.props[ORDER_STEP_DATE_PROPS[status]])
  }

  get customerId(): string {
    return this.props.customerId
  }

  get status(): OrderStatus {
    return this.props.status
  }

  // Frozen items, in the order of the cart.
  get items(): OrderItem[] {
    return this.props.items.map((item) => OrderItem.create(item))
  }

  get deliveryAddress(): OrderDeliveryAddress {
    return OrderDeliveryAddress.create(this.props.deliveryAddress)
  }

  get recipientName(): string {
    return this.props.recipientName
  }

  get deliveryInstructions(): string | null {
    return this.props.deliveryInstructions ?? null
  }

  // A copy, so callers cannot change the entity.
  get placedAt(): Date {
    return new Date(this.props.placedAt.getTime())
  }

  // Copies, or `null` while the order has not reached the step.
  get paymentApprovedAt(): Date | null {
    return this.dateOf('PAYMENT_APPROVED')
  }

  get pickingStartedAt(): Date | null {
    return this.dateOf('PICKING')
  }

  get outForDeliveryAt(): Date | null {
    return this.dateOf('OUT_FOR_DELIVERY')
  }

  get deliveredAt(): Date | null {
    return this.dateOf('DELIVERED')
  }

  // Sum of the quantities of every item.
  get itemCount(): number {
    return this.props.items.reduce((total, item) => total + item.quantity, 0)
  }

  // Sum of `lineTotalCents`; always greater than 0, since there is at least one
  // item with a price of at least 1 cent.
  get subtotalCents(): number {
    return this.items.reduce((total, item) => total + item.lineTotalCents, 0)
  }

  // 0 from `FREE_DELIVERY_THRESHOLD_CENTS`, otherwise `DELIVERY_FEE_CENTS`: the
  // same rule of the cart.
  get deliveryFeeCents(): number {
    return this.subtotalCents >= FREE_DELIVERY_THRESHOLD_CENTS
      ? 0
      : DELIVERY_FEE_CENTS
  }

  // `subtotalCents + deliveryFeeCents`.
  get totalCents(): number {
    return this.subtotalCents + this.deliveryFeeCents
  }

  toDTO(): OrderDTO {
    return {
      id: this.id,
      customerId: this.customerId,
      status: this.status,
      items: this.items.map((item) => item.toDTO()),
      deliveryAddress: this.deliveryAddress.toDTO(),
      recipientName: this.recipientName,
      deliveryInstructions: this.deliveryInstructions,
      itemCount: this.itemCount,
      subtotalCents: this.subtotalCents,
      deliveryFeeCents: this.deliveryFeeCents,
      totalCents: this.totalCents,
      placedAt: this.placedAt,
      paymentApprovedAt: this.paymentApprovedAt,
      pickingStartedAt: this.pickingStartedAt,
      outForDeliveryAt: this.outForDeliveryAt,
      deliveredAt: this.deliveredAt,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    }
  }
}

// A code generated by an external system: text with content, up to 64
// characters after trimming. `null` when it does not qualify.
function externalCode(value: unknown): string | null {
  if (typeof value !== 'string') return null

  const text = value.trim()
  return text.length > 0 && text.length <= ORDER_EXTERNAL_CODE_MAX_LENGTH
    ? text
    : null
}

// A person's name, with the same limits of the recipient name. `null` when it
// does not qualify.
function personName(value: unknown): string | null {
  if (typeof value !== 'string') return null

  const text = value.trim()
  return text.length >= ORDER_RECIPIENT_NAME_MIN_LENGTH &&
    text.length <= ORDER_RECIPIENT_NAME_MAX_LENGTH
    ? text
    : null
}

// One of `ORDER_PAYMENT_METHODS`.
function isPaymentMethod(value: unknown): value is OrderPaymentMethod {
  return (ORDER_PAYMENT_METHODS as readonly unknown[]).includes(value)
}

// Checked by tag instead of `instanceof`: `cloneWith` uses `structuredClone`,
// which can return a `Date` of another realm (e.g. the jest vm).
function isValidDate(value: unknown): value is Date {
  return (
    Object.prototype.toString.call(value) === '[object Date]' &&
    !Number.isNaN((value as Date).getTime())
  )
}

// A copy of a date, or `null` for a missing one.
function copyDate(value: Date | null | undefined): Date | null {
  return value === undefined || value === null
    ? null
    : new Date(value.getTime())
}
