export const ProductErrors = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_ALREADY_EXISTS: 'PRODUCT_SLUG_ALREADY_EXISTS',
  PRODUCT_SKU_ALREADY_EXISTS: 'PRODUCT_SKU_ALREADY_EXISTS',
  PRODUCT_NAME_TOO_SHORT: 'PRODUCT_NAME_TOO_SHORT',
  PRODUCT_NAME_TOO_LONG: 'PRODUCT_NAME_TOO_LONG',
  PRODUCT_DESCRIPTION_TOO_LONG: 'PRODUCT_DESCRIPTION_TOO_LONG',
  MONEY_CENTS_INVALID: 'MONEY_CENTS_INVALID',
  PRODUCT_LIST_PRICE_NOT_GREATER_THAN_PRICE:
    'PRODUCT_LIST_PRICE_NOT_GREATER_THAN_PRICE',
  PRODUCT_IMAGES_LIMIT_EXCEEDED: 'PRODUCT_IMAGES_LIMIT_EXCEEDED',
} as const

export type ProductErrorCode = (typeof ProductErrors)[keyof typeof ProductErrors]

// Maximum number of images a product can have.
export const PRODUCT_MAX_IMAGES = 10

// Unit used when the product does not inform one.
export const PRODUCT_DEFAULT_UNIT = 'unidade'
