export enum PasswordErrors {
  INVALID_USER = 'INVALID_USER',
  MISMATCH = 'PASSWORD_MISMATCH',
  INVALID_FORMAT = 'PASSWORD_INVALID_FORMAT',
  WEAK_PASSWORD = 'PASSWORD_WEAK',
  REUSED_RECENT_PASSWORD = 'PASSWORD_REUSED_RECENT_PASSWORD',
}
