import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Product } from '@jaja/catalog';
import { Alias } from '@mentoria-360/shared';
import { PrismaClient } from '@prisma/client';

// Brand and category are referenced by slug, since their ids are generated by
// each database.
type ProductSeedItem = {
  sku: string;
  name: string;
  slug: string;
  brandSlug: string | null;
  categorySlug: string;
  description: string | null;
  priceCents: number;
  listPriceCents: number | null;
  unit: string;
  images: { thumbUrl: string; largeUrl: string; order: number }[];
  isActive: boolean;
};

// Products already stored, deleted ones included: slug and sku stay unique
// across every row, so both are reserved.
type StoredProducts = {
  idBySku: Map<string, string>;
  skuBySlug: Map<string, string | null>;
};

type PlannedProduct = { product: Product; exists: boolean };

function loadProducts(): ProductSeedItem[] {
  const here = dirname(fileURLToPath(import.meta.url));
  const file = resolve(here, '../data/products.json');

  if (!existsSync(file)) {
    throw new Error(`[seed] catalog: products file not found. Expected at: ${file}`);
  }

  return JSON.parse(readFileSync(file, 'utf8')) as ProductSeedItem[];
}

async function loadBrandIds(prisma: PrismaClient): Promise<Map<string, string>> {
  const rows = await prisma.brand.findMany({
    where: { deletedAt: null },
    select: { id: true, slug: true },
  });
  return new Map(rows.map((row) => [row.slug, row.id]));
}

async function loadCategoryIds(prisma: PrismaClient): Promise<Map<string, string>> {
  const rows = await prisma.category.findMany({
    where: { deletedAt: null },
    select: { id: true, slug: true },
  });
  return new Map(rows.map((row) => [row.slug, row.id]));
}

async function loadStoredProducts(prisma: PrismaClient): Promise<StoredProducts> {
  const rows = await prisma.product.findMany({ select: { id: true, slug: true, sku: true } });

  const idBySku = new Map<string, string>();
  const skuBySlug = new Map<string, string | null>();
  for (const row of rows) {
    if (row.sku) idBySku.set(row.sku, row.id);
    skuBySlug.set(row.slug, row.sku);
  }
  return { idBySku, skuBySlug };
}

// Phase 1: builds and validates every product in memory, without writing
// anything, so the seed never stores data the API would reject.
function planProducts(
  items: ProductSeedItem[],
  brandIds: Map<string, string>,
  categoryIds: Map<string, string>,
  stored: StoredProducts,
): { planned: PlannedProduct[]; stats: { withoutBrand: number; suffixedSlugs: number } } {
  const planned: PlannedProduct[] = [];
  const failures: string[] = [];
  const slugOwners = new Map<string, string>();
  const stats = { withoutBrand: 0, suffixedSlugs: 0 };

  // A slug is taken when another sku uses it in this run or in the database.
  const isTaken = (slug: string, sku: string): boolean => {
    if (slugOwners.has(slug)) return slugOwners.get(slug) !== sku;
    if (stored.skuBySlug.has(slug)) return stored.skuBySlug.get(slug) !== sku;
    return false;
  };

  for (const item of items) {
    const sku = item.sku;

    // The file has unique slugs; a clash here comes from a product created
    // outside the seed, so the file's product gets the sku as a suffix.
    let slug = item.slug;
    if (isTaken(slug, sku)) {
      slug = `${item.slug}-${Alias.format(sku)}`;
      stats.suffixedSlugs++;
      if (isTaken(slug, sku)) {
        failures.push(`${sku}: slug "${item.slug}" and "${slug}" are both taken`);
        continue;
      }
    }
    slugOwners.set(slug, sku);

    // A brand missing from the database (e.g. deleted) leaves the product without brand.
    const brandId = item.brandSlug ? (brandIds.get(item.brandSlug) ?? null) : null;
    if (!brandId) stats.withoutBrand++;

    const categoryId = categoryIds.get(item.categorySlug);
    if (!categoryId) {
      failures.push(
        `${sku}: category "${item.categorySlug}" not found (run the categories seed first)`,
      );
      continue;
    }

    const result = Product.tryCreate({
      id: stored.idBySku.get(sku) ?? randomUUID(),
      name: item.name,
      slug,
      sku,
      brandId,
      categoryId,
      description: item.description,
      priceCents: item.priceCents,
      listPriceCents: item.listPriceCents,
      unit: item.unit,
      images: item.images,
      isActive: item.isActive,
    });

    if (result.isFailure) {
      failures.push(`${sku}: ${[...new Set(result.errors)].join(', ')}`);
      continue;
    }
    planned.push({ product: result.instance, exists: stored.idBySku.has(sku) });
  }

  if (failures.length) {
    throw new Error(
      `[seed] catalog: ${failures.length} products are invalid, nothing was written:\n` +
        failures.slice(0, 20).join('\n'),
    );
  }
  return { planned, stats };
}

export async function seedCatalogProducts(prisma: PrismaClient): Promise<void> {
  const items = loadProducts();

  const [brandIds, categoryIds, stored] = await Promise.all([
    loadBrandIds(prisma),
    loadCategoryIds(prisma),
    loadStoredProducts(prisma),
  ]);

  const { planned, stats } = planProducts(items, brandIds, categoryIds, stored);

  // Phase 2: upsert by sku, one transaction per product. The images are replaced
  // as a whole; `deletedAt` is never touched, so a deleted product stays deleted.
  for (const { product } of planned) {
    const sku = product.sku!;
    const fields = {
      name: product.name,
      slug: product.slug,
      brandId: product.brandId,
      categoryId: product.categoryId,
      description: product.description,
      priceCents: product.priceCents,
      listPriceCents: product.listPriceCents,
      unit: product.unit,
      isActive: product.isActive,
    };
    const images = product.images;
    const nestedImages = images.length ? { images: { createMany: { data: images } } } : {};

    await prisma.$transaction([
      prisma.productImage.deleteMany({ where: { product: { sku } } }),
      prisma.product.upsert({
        where: { sku },
        create: { id: product.id, sku, ...fields, ...nestedImages },
        update: { ...fields, ...nestedImages },
      }),
    ]);
  }

  const created = planned.filter(({ exists }) => !exists).length;
  console.log(
    `[seed] catalog: ${planned.length} products upserted by sku — ${created} created, ` +
      `${planned.length - created} updated, ${stats.withoutBrand} without brand, ` +
      `${stats.suffixedSlugs} slugs suffixed with the sku`,
  );
}
