export const CustomerErrors = {
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ALREADY_EXISTS: 'CUSTOMER_ALREADY_EXISTS',
  CUSTOMER_CPF_ALREADY_EXISTS: 'CUSTOMER_CPF_ALREADY_EXISTS',
  CUSTOMER_USER_NOT_FOUND: 'CUSTOMER_USER_NOT_FOUND',
  CUSTOMER_ZIP_CODE_INVALID: 'CUSTOMER_ZIP_CODE_INVALID',
  CUSTOMER_STATE_INVALID: 'CUSTOMER_STATE_INVALID',
  CUSTOMER_LOCATION_INVALID: 'CUSTOMER_LOCATION_INVALID',
} as const

export type CustomerErrorCode =
  (typeof CustomerErrors)[keyof typeof CustomerErrors]
